apiVersion: v1
kind: Service
metadata:
  name: im-challenge-service
spec:
  selector:
    app: im-challenge
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5002
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-challenge
spec:
  replicas: 4
  selector:
    matchLabels:
      app: im-challenge
  template:
    metadata:
      labels:
        app: im-challenge
    spec:
      containers:
      - name: im-challenge
        image: im-challenge:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
